services:
    _defaults:
        autowire: true
        autoconfigure: true

    Symfony\Component\Uid\AbstractUid:
      class: Symfony\Component\Uid\UuidV4

    App\Common\Domain\Message\MessageBusInterface:
      class: App\Common\Application\Message\MessageBus