parameters:
    app.env: '%env(APP_ENV)%'
    app.domain: '%env(APP_DOMAIN)%'
    app.scheme: '%env(APP_SCHEME)%'

    kafka.global:
        group.id: '%env(string:RD_KAFKA_GROUP_ID)%'
        metadata.broker.list: '%env(string:RD_KAFKA_BROKER_LIST)%'
        enable.auto.commit: 'false'
    kafka.topic:
        auto.offset.reset: beginning

services:
    _defaults:
        autowire: true
        autoconfigure: true
