services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Common\Infrastructure\DI\Config\KafkaConfig:
        arguments:
            $globalConfig: '%kafka.global%'
            $topicConfig: '%kafka.topic%'

    Interop\Queue\ConnectionFactory:
        class: Enqueue\RdKafka\RdKafkaConnectionFactory
        arguments:
            $config:
                global: '%kafka.global%'
                topic: '%kafka.topic%'
