common_api:
    resource: ../src/Common/Infrastructure/Controller/Api
    type: attribute
    stateless: false
    prefix: /api

user_api:
    resource: ../src/User/Infrastructure/Controller/Api
    type: attribute
    stateless: false
    prefix: /api