api_users:
    resource: ../src/User/Infrastructure/Controller/Api
    type: attribute
    stateless: false
    prefix: /api

api_common:
    resource: ../src/Common/Infrastructure/Controller/Api
    type: attribute
    stateless: false
    prefix: /api