api_users:
    resource: ../src/User/Presentation/Api
    type: attribute
    stateless: false
    prefix: /api

api_common:
    resource: ../src/Common/Presentation/Api
    type: attribute
    stateless: false
    prefix: /api