common_api:
    resource: ../src/Common/Infrastructure/Controller
    type: attribute
    stateless: false
    prefix: /api

auth_api:
    resource: ../src/Auth/Infrastructure/Controller
    type: attribute
    stateless: false
    prefix: /api

cart_api:
    resource: ../src/Cart/Infrastructure/Controller
    type: attribute
    stateless: false
    prefix: /api

api_login_check:
    path: /api/login_check